### ISSUE TITLE
Document what happens if an issue is not in a project

### ISSUE THREAD

**Issue by koppor** [m7kvqbe1/github-action-move-issues#3]
(Risen by https://github.com/JabRef/jabref/pull/11952#pullrequestreview-2365472252)

I think, this action does nothing if an issue is not inside a project. Nevertheless, this should be documented in the `README.md`.

**Comment by m7kvqbe1** [comment]
The action will add the issue to the specified project if it's not already in there.

https://github.com/m7kvqbe1/github-action-move-issues/blob/1e86cdff05ba4cf0e75a9412fcf19c12280238d2/index.js#L125
